// Embedding VBR inside Rust.
//
// Write VBR in a `// vbr:begin … // vbr:end` comment block, then run
//
//     cargo run -- embed examples/rust_embedding/sum_of_squares.rs
//
// and the transpiler fills the `// vbr:gen … // vbr:gen-end` region below it with
// the Rust your VBR became — re-running just overwrites that region. Because the
// VBR stays a comment, this file always compiles; the generated Rust is real code
// spliced into the same function, so the VBR can call Rust functions (`square`),
// read Rust variables in scope (`limit`), and leave its own variables (`total`)
// for the Rust around it to use.

fn square(n: i64) -> i64 {
    n * n
}

fn sum_of_squares(limit: i64) -> i64 {
    // vbr:begin
    //   Dim total As Long = 0
    //   Dim i As Long
    //   For i = 1 To limit
    //       total = total + square(i)
    //   Next
    // vbr:end
    // vbr:gen (generated by `vbr embed` — do not edit)
    let mut total: i64 = 0;
    for i in 1..=limit {
        total = total + square(i);
    }
    // vbr:gen-end
    total
}

fn main() {
    println!("sum of squares 1..=5 = {}", sum_of_squares(5));
}
